defaults: &defaults

production:
  database: logstew_production
  uri: mongodb://md1.internal:27017

development:
  <<: *defaults
  database: logstew_development
  uri: mongodb://localhost:27017

test:
  <<: *defaults
  database: logstew_test
  uri: mongodb://localhost:27017
