dev_defaults: &dev_defaults
  uri: mongodb://localhost:27017

production:
  database: logstew_production
  uri: mongodb://md1.internal:27017

development:
  <<: *dev_defaults
  database: logstew_development

test:
  <<: *dev_defaults
  database: logstew_test
